// Generated by tools/voiceover.py: one clip per line, placed on the frame
// where its words appear. Voice: Kokoro af_heart, speed 0.94.
export const VOICE_OVER: { id: string; from: number; frames: number; text: string }[] = [
  {
    "id": "open",
    "from": 16,
    "frames": 57,
    "text": "When the sun goes down on the Red Sea,"
  },
  {
    "id": "night",
    "from": 125,
    "frames": 30,
    "text": "we run the night."
  },
  {
    "id": "kids",
    "from": 180,
    "frames": 28,
    "text": "The kids club."
  },
  {
    "id": "theme",
    "from": 225,
    "frames": 32,
    "text": "The theme nights."
  },
  {
    "id": "daytime",
    "from": 270,
    "frames": 34,
    "text": "The daytime line."
  },
  {
    "id": "reviews",
    "from": 312,
    "frames": 49,
    "text": "So your guests write the reviews."
  },
  {
    "id": "shows",
    "from": 378,
    "frames": 90,
    "text": "Fire shows. Light shows. Full theme nights."
  },
  {
    "id": "nostudio",
    "from": 536,
    "frames": 118,
    "text": "No studio, no extras. Real guests, on ordinary nights."
  },
  {
    "id": "team",
    "from": 672,
    "frames": 114,
    "text": "One resident team, living at your hotel, seven nights a week."
  },
  {
    "id": "casablue",
    "from": 852,
    "frames": 132,
    "text": "Casa Blue: number two, of a hundred and eight hotels in Marsa Alam."
  },
  {
    "id": "earlier",
    "from": 1000,
    "frames": 117,
    "text": "Before that: Solymar Reef, Jaz Grand, and the Hilton Nubian."
  },
  {
    "id": "guests",
    "from": 1158,
    "frames": 77,
    "text": "And guests name our team, in their own reviews."
  },
  {
    "id": "method",
    "from": 1446,
    "frames": 151,
    "text": "Nothing runs on hope. Every event has an owner, and every month, you get the report."
  },
  {
    "id": "cta",
    "from": 1626,
    "frames": 34,
    "text": "Let's run your night."
  },
  {
    "id": "proposal",
    "from": 1725,
    "frames": 58,
    "text": "Request your proposal on WhatsApp."
  }
];
